config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' 
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do 
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts
  # , only: :create
  # get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    # Contact form validations
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user  
<<<<<<< HEAD
=======
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
>>>>>>> NOW
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
<<<<<<< HEAD
=======
  def email_required?
    false
  end

  def email_changed?
    false
  end

>>>>>>> NOW
  
  attr_accessor :stripe_card_token
  # If Pro user passes validations (email, password, etc),
  # then call Stripe and tell Stripe to set up a subscription
  # upon charging the customers card.
  # Stripe responds back w customer data. Store customer.id as
  # the customer token and save the user.
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
# Whitelist the following form fields so that we can process them, if coming
# from a Devise sign up form.
protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end
  # POST request /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to database
    if @contact.save
      # Store form fields via parameters, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variables into ContactMailer
      # and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash
      # and redirect to new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path 
    else
      # If Contact method doesn't save,
      # store errors in flash hash,
      # and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private
    # To collect data from form, we need to
    # use strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET request for / which is our homepage
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
  
  def p1zz4b07
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
   @profile = Profile.new 
  end
  
  # POST to /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out form
    @user = User.find( params[:user_id])
    # Create profile linked to this specific user
    @profile = @user.build_profile( profile_params)
    if @profile.save
      flash[:success] = "Profile updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit 
    @user = User.find( params[:user_id])
    @profile = @user.profile
  end
  
   # PATCH to /users/:user_id/profile
  def update 
    # retrieve user from database
    @user = User.find( params[:user_id] )
    # retrieve user's profile
    @profile = @user.profile
    # mass assign edited profile attributes and save(update)
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      #Redirect user to profile page
      redirect_to user_path(id: params[:user_id] )
    else
      render action: :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:username, :first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  
  # Extend default Devise gem behavior so that users signing up w Pro Acct
  # (plan ID 2) save w special Stripe subscription function.
  # Otherwise Devise signs up user as usua.
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Go head, getchyoself a plan."
        redirect_to root_url
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.includes(:profile)
  end
  
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon
    if @user.profile.job_title == "Developer"
     "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="row">
      <!--<h2 class="text-center", style="font-size:420%; margin-bottom: -48px;  z-index: +1; position:relative;">sub</h2>-->
    </div>
    <div class="col-md-6 col-md-offset-3">
      <div class="", style="z-index: -1, color: blue">  
        <%= form_for @contact do |f| %>
          <!--<div class="form-group">-->
          <!--  <%= f.label :"♡ from" %>-->
          <!--  <%= f.text_field :name, class: 'form-control' %>-->
          <!--</div> -->
          
          <!--<div class="form-group">-->
          <!--  <%= f.label :from, 'who', class: 'navbar-brand' %>-->
          <!--  <%= f.text_field :email, class: 'form-control' %>-->
          <!--</div> -->
          
          <div class="form-group">  
            <%= f.label :🎬, class: 'navbar-brand' %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div> 
          
            <%= f.submit 'Send', class: 'navbar-brand form-group-btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>💜</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Orbitron|Press+Start+2P|Freckle+Face|Special+Elite:400,700,800,900,1000,1100" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  </head>

  <body>
    <!--<nav class="navbar navbar-default navbar-fixed-top" role="navigation">-->
      
      <!--<div class='container ' >-->
        
    <!--    <div class="navbar-header">-->
          
          <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">-->
          <!--  <span class="sr-only">Toggle navigation</span>-->
          <!--  <span class="icon-bar"></span>-->
          <!--  <span class="icon-bar"></span>-->
          <!--  <span class="icon-bar"></span>-->
          <!--</button>-->
          <%= link_to root_path, class: "navbar-brand everythingOnOneLine" do %>
            <!--now-->
            <!--<div class="navbar-music">-->
            <!--  <iframe src="https://embed.spotify.com/?uri=spotify%3Auser%3Akeltontunes%3Aplaylist%3A0k5kve5va7xJCMJTxofUgJ" width="80" height="80" frameborder="0" allowtransparency="true"></iframe>-->
            <!--</div>-->
          <% end %>
          

          
          <!--<ul class="mail everythingOnOneLine " style="list-style-type: none; white-space: wrap;display: inline-block;">          -->
          <!--  <% if current_page?(root_path) %>-->
          <!--  <%= link_to "♡", new_contact_path, class: "navbar-brand" %>-->
          <!--  <% end %>-->
          <!--  <%= link_to "💌", new_contact_path %>-->
          <!--  <% if current_page?(root_path) %>-->
          <!--  <%= link_to "x", new_contact_path %>  show some stuff-->
          <!--  <% end %>-->
          <!--  <% if current_page?(contacts_path) %>-->
          <!--  <%= link_to "Y", new_contact_path %>  show some stuff-->
          <!--  <% end %>-->
          <!--</ul>-->
        </div>

<!--<div class="navbar-right">-->

<!--  <% if user_signed_in? %>-->
<!--    <%= link_to "✌️", destroy_user_session_path, method: :delete, class: "btn navbar-btn" %>-->
<!--  <% else %>-->
    <!--<%= link_to "🖖", new_user_session_path, class: "btn navbar-btn" %>-->
<!--    <%= link_to "🎟", new_user_registration_path, class: "btn navbar-btn" %>-->
<!--  <% end %>-->
 
<!--</div>-->

  
<ul class="nav navbar-nav navbar-right" style="font-size:100%;">
  <!--<% if user_signed_in? %>-->
  <li><%= link_to "community", users_path %></li>
  <li><%= link_to "my acct", edit_user_registration_path %></li>
  <li><%= link_to "❔", new_contact_path %></li>
  <li><%= link_to "Contact Us", new_contact_path %></li>
  <!--<% end %>-->
</ul>

        
      </div>
    </nav>
    
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>  
    </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="content container text-left ">
<<<<<<< HEAD
    <h2>We are Jig, we believe  💬💞️💬 will change the 🌐. Let's ➰ ️<h2>
=======
    <h2>We are Jig, we believe  💬💞️💬 will change the 🌐. Let's 🌱 💭 ️<h2>
>>>>>>> NOW
    <!--<p style="font-size: 24px; margin-top: 20px;margin-bottom: 10px;">-->
    <!--We are DevMatch. Our company focuses on creating an exclusive community-->
    <!--for developers and entrepreneurs to meet. 🎈-->
    <!--</p>-->
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path,  html: { multipart: true }  do |f| %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <!--<div class="form-group">-->
  <!--  <%= f.label :last_name %>-->
  <!--  <%= f.text_field :last_name, class: 'form-control' %>-->
  <!--</div>-->
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar , class: 'form-control' %>
  </div> 
  <div class="form-group">
    <%= f.label :jig %>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>
  <!--<div class="form-group">-->
  <!--  <%= f.label :job_title %>-->
  <!--  <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>-->
  <!--</div>-->
  <!--<div class="form-group">-->
  <!--  <%= f.label :phone_number %>-->
  <!--  <%= f.text_field :phone_number, class: 'form-control' %>-->
  <!--</div>-->
  <!--<div class="form-group">-->
  <!--  <%= f.label :contact_email %>-->
  <!--  <%= f.text_field :contact_email, class: 'form-control' %>-->
  <!--</div>-->
  <!--<div class="form-group">-->
  <!--  <%= f.label :jig %>-->
  <!--  <%= f.text_area :description, class: 'form-control' %>-->
  <!--</div>-->
  <div class="form-group">
    <%= f.submit "🤘", class: 'btn btn-blockz btn-center' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center", style="font-size: 700%; margin-top: -15px">✨</h1>
      <!--<p class="text-center">Get Involved!</p>-->
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>  
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center" style="font-size: 500%; margin-top:-19px;">👶</h1>
      <!--<p class="text-center">Get Involved!</p>-->
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>  
  </div>
</div>

app/views/users/index.html.erb
<div class="container", style="max-width: 100%">
  <div class="row", style="max-width: 100%">
    <div class="col-md-8 col-md-offset-2", style="max-width: 100%">
      <ul class="list-unstyled", style="max-width: 100%">
        <% @users.each do |user| %>
          <% if user.profile %> 
          <li>
            <div class="well row <%= cycle('white-bg', '') %> ">
              <div class="col-sm-4 text-center">
                <% if user.profile.avatar %>
                  <div class="disco">
                  </div>
                  <%= link_to user do %>
                    <%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
                  <% end %>
                <% end %>
                
              </div>
              <div>
                <%= link_to user do %>
                  <h2 style="font-size: 240%; color: #88B04B!important"><%= user.profile.first_name %><%= user.profile.last_name %></h2>
                    
                <% end %> 
                  
                  <!--<p>-->
                  <!--  <%= user.profile.job_title %>-->
                  <!--  <% if user.plan_id == 2 %>-->
                  <!--    <span class="label label-success">PRO</span>-->
                  <!--  <% end %>-->
                  <!--</p>-->
              </div>
            </div>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container", style="max-width: 100%; margin-top:-19px">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img'  %>
        <h1 style="max-width: 100%; margin-top:-1px"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
        <div class="btn-jigz", style="max-width: 100%; margin-top: -10px">
          <%= @user.profile.description %>
        </div>
      
      
      </div>
      <!--<div class="col-md-3 text-center", style="display: block; max-width: 100%; nowrap">-->
        <!--<h1 style="max-width: 100%"><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>-->
        <!--<h3><span class="job_title_icon"><%= job_title_icon %></span><%= @user.profile.job_title %></h3>-->
        
        <!--<% if current_user.plan_id == 2 %>-->
        <!--  <div class="well profile-block profile-contact-info">-->
        <!--    <%= @user.profile.phone_number %>-->
        <!--    <%= @user.profile.contact_email %>-->
        <!--  </div>-->
        <!--<% end %>-->
      <!--</div>-->
    </div>
  
</div>